
spring:
  datasource:
    url: jdbc:mysql://192.168.1.254:3306/springboot?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: shihuai1993A


